version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'shorten_url'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    expose:
      - '3306'
      
  url-shortener:
    image: url-shortener-service
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
    ports:
      - '8080:8080'
    expose:
      - '8080'